# Generated by Django 2.2.27 on 2022-04-03 08:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20220403_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2022, 4, 3, 11, 46, 22, 451085), verbose_name='Опубликовано'),
        ),
    ]
